spring.datasource.url=jdbc:h2:mem:arq_software
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.sql.init.mode=always

spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=${ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${SECRET_KEY}

aws.order-event=T03N-JOAO-PEDRO-FREITAS.fifo

#aws.sqs.queue.saida-estoque=SQS-SAIDA-ESTOQUE.fifo
#aws.sqs.queue.entrada-estoque=SQS-ENTRADA-ESTOQUE.fifo
